deploy:stg:
  stage: deploy
  only:
    - staging
  script:
    - echo "Deploying to STG..."
    - rsync -az --delete ./ "$SSH_USER@$STG_HOST:~/app/"
    - |
      ssh "$SSH_USER@$STG_HOST" <<'EOF'
      cd ~/app
      npm install --production
      pm2 restart myapp || pm2 start server.js --name "myapp"
      pm2 save
      EOF