deploy:prod:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying to PROD..."
    - rsync -az --delete ./ "$SSH_USER@$PROD_HOST:~/app/"
    - |
      ssh "$SSH_USER@$PROD_HOST" <<'EOF'
      cd ~/app
      npm install --production
      pm2 restart app || pm2 start server.js --name "app"
      pm2 save
      EOF
