deploy:dev:
  stage: deploy
  only:
    - develop
  script:
    - echo "Deploying to DEV..."
    - rsync -az --delete ./ "$SSH_USER@$DEV_HOST:~/app/"
    - |
      ssh "$SSH_USER@$DEV_HOST" <<'EOF'
      cd ~/app
      npm install --production
      pm2 restart app || pm2 start server.js --name "app"
      pm2 save
      EOF